source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'SwiftLib' do
pod 'YYKit'
pod 'NIMSDK'
pod 'Alamofire'
pod 'SnapKit'
pod 'Kingfisher'
pod 'LFLiveKit'
pod 'SwiftDate'
end

